#############################################################################
# Makefile for building C:\hexpand\hexp.exe
# Generated by tmake at 22:13, 2019/01/09
#     Project: C:\hexpand\hexp.pro
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	cl
CXX	=	cl
CFLAGS	=	-nologo -W3 -O1 -GX 
CXXFLAGS=	-nologo -W3 -O1 -GX 
INCPATH	= -IC:\OSL\include
LIBPATHS = /LIBPATH:C:\OSL\lib /LIBPATH:"C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib"
LINK	=	link
LFLAGS	=	/NOLOGO /incremental:no /nodefaultlib:"libcmt" /SUBSYSTEM:Console
LIBS	=	libcryptoMD.lib libcryptoMDd.lib libcryptoMT.lib libcryptoMTd.lib libsslMD.lib libsslMDd.lib libsslMT.lib libsslMTd.lib libcmt.lib msvcrtd.lib msvcrt.lib Crypt32.Lib libeay32.lib ssleay32.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib imm32.lib winmm.lib wsock32.lib comctl32.lib
MOC	=	$(QTDIR)\bin\moc.exe
UIC	=	$(QTDIR)\bin\uic.exe
REMOVE	=	-del
RMDIR	=	-rmdir /q /s
ZIP	=	zip -r -9

####### Files

HEADERS =	byteorder.h \
		hexpand.h
SOURCES =	hexpand.c \
		main.c
OBJECTS =	hexpand.obj \
		main.obj
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	C:\hexpandw\hexpand.exe
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.C.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

####### Build rules



all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(REMOVE) $(TARGET) 
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<<
	    $(OBJECTS) $(OBJMOC) $(LIBPATHS) $(LIBS) $(NLIBS) 
<<

moc: $(SRCMOC)

tmake:
	tmake C:\hexpandw\hexp.pro

dist:
	$(REMOVE) Makefile *.dsp *.dsw *.opt *.ncb *.mak

clean:
	$(REMOVE) $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	$(REMOVE) C:\hexpandw\hexp.opt

	$(RMDIR) Debug Release


####### Compile

hexpand.obj: hexpand.c

main.obj: main.c

